// 开票
export const SET_TICKET_OBJ = 'SET_TICKET_OBJ'

export const SET_TICKET_DETAIL = 'SET_TICKET_DETAIL'

// 付款
export const SET_PAY_OBJ = 'SET_PAY_OBJ'

export const SET_DETAIL_PARAMS = 'SET_DETAIL_PARAMS'

// 入库
export const SET_STORAGE_OBJ = 'SET_STORAGE_OBJ'

export const SET_PAY_PARAMS = 'SET_PAY_PARAMS'

export const SET_TICKET_PARAMS = 'SET_TICKET_PARAMS'

export const SET_STORAGE_PARAMS = 'SET_STORAGE_PARAMS'

export const GET_INVOICE_ORDER_TYPE = 'GET_INVOICE_ORDER_TYPE'

export const GET_INVOICERTYPE = 'GET_INVOICERTYPE'


