export const F_GET_TYPE = 'F_GET_TYPE'
export const F_GET_CODE = 'F_GET_CODE'
export const F_GET_PAYINFO = 'F_GET_PAYINFO'
export const F_GET_INVOICETYPE = 'F_GET_INVOICETYPE'
export const F_GET_INVOICECODE = 'F_GET_INVOICECODE'
export const F_QUERT_ORDERINFO = 'F_QUERT_ORDERINFO'
export const GET_ORDER_PRICE_INFO = 'GET_ORDER_PRICE_INFO'
export const QUERY_PAYINFO_LIST = 'QUERY_PAYINFO_LIST'

