export const INSURANCE_GET_ORGANIZATIONS = 'INSURANCE_GET_ORGANIZATIONS' // 获取保险机构名称

export const GET_INSERT_OVER = 'GET_INSERT_OVER'

export const GET_COCODE = 'GET_COCODE'

export const GET_COCODE_DETAIL = 'GET_COCODE_DETAIL'

export const TO_INSERT_OR_UPDATA = 'TO_INSERT_OR_UPDATA'

export const GET_COST_DETAIL = 'GET_COST_DETAIL'
