
//线索总数
export const DCC_FOLLOW_UP_CONDITION_STATISTICS_GET_FLOW_LIST = 'DCC_FOLLOW_UP_CONDITION_STATISTICS_GET_FLOW_LIST'
// 来源渠道
export const DCC_FOLLOW_UP_GET_SUPPLIER_TYPES = 'DCC_FOLLOW_UP_GET_SUPPLIER_TYPES'
// 分页对象
export const DCC_FOLLOW_UP_FLOWLIST_PAGES = 'DCC_FOLLOW_UP_FLOWLIST_PAGES'
// 对应店的店员
export const DCC_FOLLOW_UP_GET_SPECIALIST = 'DCC_FOLLOW_UP_GET_SPECIALIST'
// 所有的DCC
export const ALL_DCC = 'ALL_DCC'
// 筛选后的dcc店员
export const DCC_FOLLOW_UP_FILTER_SPECIALIST = 'DCC_FOLLOW_UP_FILTER_SPECIALIST'
// 表头的月份
export const TOTAL_MONTH = 'TOTAL_MONTH'