export const MENU_GET_MENUS = 'MENU_GET_MENUS'
export const MENU_SET_ADD_MODAL = 'MENU_SET_ADD_MODAL'
export const MENU_SET_UPDATE_MODAL = 'MENU_SET_UPDATE_MODAL'
export const MENU_SET_SELECTED_ROW = 'MENU_SET_SELECTED_ROW'
