//用来给当前模块的mutation里的方法来命名的 官方上叫事件类型

export const  FINANCE_ADD_FINANCE = 'FINANCE_ADD_FINANCE'

export const  FINANCE_UPDATA_FINANCE = 'FINANCE_UPDATA_FINANCE'

export const  SET_PARAMS = 'SET_PARAMS'

export const  FINANCE_ADD_FINANCECODE = 'FINANCE_ADD_FINANCECODE'

export const  FINANCE_ADD_FINANCEAddFLAG = 'FINANCE_ADD_FINANCEAddFLAG'

export const  FINANCE_ADD_FINANCEACTIVEFLAG = 'FINANCE_ADD_FINANCEACTIVEFLAG'

export const  PRESERVE_SHOP = 'PRESERVE_SHOP'

export const SET_QUERYPARAMS = 'SET_QUERYPARAMS'

export const  FINANCE_SET_SHOPDATA = 'FINANCE_SET_SHOPDATA'

export const  FINANCE_SET_SALESDATA = 'FINANCE_SET_SALESDATA'

export const  FINANCE_SET_GOVERNMENTDATA = 'FINANCE_SET_GOVERNMENTDATA'

export const  FINANCE_SET_SETTABACATIVE = 'FINANCE_SET_SETTABACATIVE'

export const GET_DATALIST = 'GET_DATALIST'

export const SETINTERSUBSIDYDATA = 'SETINTERSUBSIDYDATA'

export const SETINTEREST = 'SETINTEREST'

export const SETPOUNDAGE = 'SETPOUNDAGE'

export const UPDATAFINANCEID = 'UPDATAFINANCEID'