export const SUPPLIER_INVOICE_GET_INVOICE_TYPES = 'SUPPLIER_INVOICE_GET_INVOICE_TYPES'
export const SUPPLIER_INVOICE_GET_INVOICE_INFO_LIST = 'SUPPLIER_INVOICE_GET_INVOICE_INFO_LIST'
export const SUPPLIER_INVOICE_SET_PAGER = 'SUPPLIER_INVOICE_SET_PAGER'
export const GET_DATA_LIST = 'GET_DATA_LIST'